# Generated by Django 4.1.2 on 2022-12-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=255)),
                ('recipe', models.TextField()),
                ('description', models.TextField()),
                ('category', models.ManyToManyField(related_name='category', to='backend.category')),
                ('ingredient', models.ManyToManyField(related_name='Recipe_ingredient', to='backend.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='ingredient',
            field=models.ManyToManyField(related_name='ingredient', to='backend.ingredient'),
        ),
    ]
