# Generated by Django 4.1.2 on 2022-12-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
    ]
