# Generated by Django 4.1.2 on 2022-12-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='cuisine',
        ),
    ]
