# Generated by Django 4.1.2 on 2022-12-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_rename_category_name_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="category",
            new_name="ingredient",
        ),
    ]
