# Generated by Django 4.1.2 on 2022-12-08 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_rename_category_ingredient_ingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="ingredient",
            new_name="category",
        ),
    ]
