# Generated by Django 4.1.2 on 2022-12-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_rename_ingredient_ingredient_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
