# Generated by Django 4.1.2 on 2022-12-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_recipe_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.ImageField(null=True, upload_to="static/media"),
        ),
    ]
