# Generated by Django 4.1.2 on 2022-12-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_alter_recipe_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("dish", models.TextField()),
                ("image", models.ImageField(null=True, upload_to="static/media")),
            ],
        ),
        migrations.RenameField(
            model_name="ingredient",
            old_name="category",
            new_name="cuisine",
        ),
        migrations.RenameModel(
            old_name="Category",
            new_name="Cuisine",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.AddField(
            model_name="dish",
            name="cuisine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dishes",
                to="backend.cuisine",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="dishes", to="backend.ingredient"
            ),
        ),
    ]
