# Generated by Django 4.1.2 on 2022-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_dish_rename_category_ingredient_cuisine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuisine",
            name="image",
            field=models.ImageField(null=True, upload_to="static/media"),
        ),
    ]
